Topic	Time Complexity
Array Traversal	O(n)
Maximum Element	O(n)
Minimum Element	O(n)
Average	O(n)
Linear Search	O(n)
Binary Search	O(log n)
Bubble Sort	O(n²)
Previous Greater Element	O(n)
Sum of Digits	O(d)
Factorial	O(n)
Reverse Linked List	O(n)
Queue Full Check	O(1)
Queue Empty Check	O(1)
Inorder Traversal	O(n)
Postorder Traversal	O(n)